### ISSUE TITLE
Validation on DAVIS 2016

### ISSUE THREAD

**Issue by hellboywyh** [seoungwugoh/STM#39]
When  I run the pre-trained model on DAVIS2016, the error comes. I downloaded the DAVIS 2016 from the official website. There is no file named "ImageSets/2016/val.txt".

(openmmlab) root@bh1llmn592poa-0:/yhwang/0-Projects/11-mmsegmentation/STM# python eval_DAVIS.py -g '1' -s val -y 16 -D ../STCN/dataset/DAVIS/2016
Space-time Memory Networks: initialized.
STM : Testing on DAVIS
Traceback (most recent call last):
  File "eval_DAVIS.py", line 101, in <module>
    Testset = DAVIS_MO_Test(DATA_ROOT, resolution='480p', imset='20{}/{}.txt'.format(YEAR,SET), single_object=(YEAR==16))
  File "/yhwang/0-Projects/11-mmsegmentation/STM/dataset.py", line 28, in __init__
    with open(os.path.join(_imset_f), "r") as lines:
FileNotFoundError: [Errno 2] No such file or directory: '../STCN/dataset/DAVIS/2016/ImageSets/2016/val.txt'

**Comment by hding2455** [comment]
I met the same issue and I just found that you need to use DAVIS/2017/trainval as the DATA_ROOT instead of DAVIS/2016. Hope this helps
